# Generated by Django 2.1 on 2018-08-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='thumb_url',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
