# Generated by Django 2.1 on 2018-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180825_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='link',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video',
            field=models.CharField(default='lala', max_length=10),
            preserve_default=False,
        ),
    ]
