# Generated by Django 2.1 on 2018-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180825_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=10)),
            ],
        ),
    ]
